### ISSUE TITLE
Total disk space on resources tab

### ISSUE THREAD

**Issue by petermezei** [slamby/slamby-insight#11]
We should display total / free disk space instead of just free.

- [x] Put form in

**Comment by attilalaszlo** [comment]
For this an API feature needed.
See this issue: slamby/slamby-api#6

**Comment by petermezei** [comment]
@sbeci could you check it? It should be a tiny but nice one.

**Comment by petermezei** [comment]
I proposed it to Release 1.3.0

**Comment by petermezei** [comment]
@sbeci any news about this?
