### ISSUE TITLE
Tag copy, copy all to

### ISSUE THREAD

**Issue by petermezei** [slamby/slamby-insight#18]
Copy selected or all tags from a dataset to another one. Copy tags, select target dataset and copy it.

Put a new button in the header, next to the export words and delete buttons. Lets call it "Copy". Once at least one tag is selected, Copy button is enabled (otherwise it disabled).

Once we click the copy button, a dataset selector pops up. We select the target dataset, and the copy process starts.

Questions:
1. What happens if there is a tag in the target dataset with the same id?
2. Should we copy all the tags, or just the selected one (I would prefer it)
3. What happens if there are already existing tags under the target dataset? I wouldnt manage it. Users can check it, and remove all the tags, then copy them.

@attilalaszlo @sbeci

**Comment by attilalaszlo** [comment]
done #39

**Comment by petermezei** [comment]
Seems to be ok.
