### ISSUE TITLE
Application Icon

### ISSUE THREAD

**Issue by OrselSani** [slamby/slamby-insight#2]
Application icon should be renewed at welcome page.

![slamby-app-icon](https://cloud.githubusercontent.com/assets/18461540/19067368/10cf8d0c-8a1e-11e6-85ef-2920c905b35f.png)
![slamby-app-icon](https://cloud.githubusercontent.com/assets/18461540/19067367/10cda6ea-8a1e-11e6-9579-e0605c2b301b.jpg)

Note: Files are attached as JPG and PNG with(out) background

**Comment by illeszsolt** [comment]
Replaced the icon on Welcome Page.
