### ISSUE TITLE
Insight statistics

### ISSUE THREAD

**Issue by petermezei** [slamby/slamby-insight#20]
Statistics tab for Insight. Displaying API statistics data. For start a data grid can be suitable.
Display each available data from API response in a grid.

Future enhancement tips: chart display.

**Comment by petermezei** [comment]
Ok I got this. Just started this, but I found we have an older angular2-sdk that does not contain StatisticsApi. @attilalaszlo  could you help me please compiling a latest angular2 sdk?

I checked the code, I can manage this.

My working branch: https://github.com/slamby/slamby-insight/tree/feature/insight-statistics%2320

**Comment by attilalaszlo** [comment]
merged to master #36

**Comment by petermezei** [comment]
It might worth to select the latest available statistics date in the dropdown list.

**Comment by attilalaszlo** [comment]
I did it in this commit: 4e04aa0577951725285088f6d733bdd7d96a4b16
