### ISSUE TITLE
Tag export

### ISSUE THREAD

**Issue by petermezei** [slamby/slamby-insight#23]
Export tags into a fixed format file. Be able to import the exported file as a taglist.

**Comment by attilalaszlo** [comment]
done, accidentally commited to the service clone branch

**Comment by attilalaszlo** [comment]
there is a new button on the datasets->tags page, named: Export Tags
All the available tags will be exported to the selected file in CSV format

**Comment by petermezei** [comment]
Could you block the export button till the tags are loaded?

**Comment by attilalaszlo** [comment]
done
