### ISSUE TITLE
PRC service: index form filter doesnt work properly.

### ISSUE THREAD

**Issue by petermezei** [slamby/slamby-insight#3]
PRC Index filter input field does not work properly.

Suggestion:
- we should change the input type text to textarea,
- handle filter object based on the API documentation:

Filter: {
   "Query": "status:1",
   "TagIdList": [1,2,3,7,9]
}

@attilalaszlo could you validate my suggestions?
@sbeci could you check it please once Atis validated it?

![image](https://cloud.githubusercontent.com/assets/18461114/20483496/8d016c0c-aff2-11e6-8318-51bb5a2ef3e1.png)

![image](https://cloud.githubusercontent.com/assets/18461114/20483538/bd4def5c-aff2-11e6-9b40-f22118c1904c.png)

https://developers.slamby.com/docs/API/v1.0.0/service#index

**Comment by attilalaszlo** [comment]
fixed. Will be released in 1.0.2

looks like this:
![image](https://cloud.githubusercontent.com/assets/16559709/21098589/3cfa3b98-c06a-11e6-948b-e5ca7e9d5675.png)
