### ISSUE TITLE
Classifier Activate Settings buttons broke after unsuccessful search service activation.

### ISSUE THREAD

**Issue by petermezei** [slamby/slamby-insight#33]
Insight version: 1.3.17026.01 portable
API version: 1.4.17030.02

On Skye I have two demo services: one classifier and one search.

Classifier service is deactivated. My search service is prepared, but not activated.

Once I click the search service activation I set the classifier service as a related service, then click the activation button, but I got an error message: the classifier service is not activated. This is right.

So I try to activate the classifier service, but now the window broke.

![image](https://cloud.githubusercontent.com/assets/18461114/22464248/36787136-e7b6-11e6-8c23-792bbe4ebe09.png)

(Before the failed search activation the classifier activation window worked fine.)

**Comment by attilalaszlo** [comment]
the problem was only in that specific version, bug fixed
