### ISSUE TITLE
Internal Error: Cannot call function getAppPath

### ISSUE THREAD

**Issue by petermezei** [slamby/slamby-insight#40]
Using Insight services tab, and creating services, randomly Internal Error messages pops.

![image](https://cloud.githubusercontent.com/assets/18461114/22740942/d094206a-ee11-11e6-9b6e-7219929b1793.png)

Todo:

- [ ] Reproducing this issue.

**Comment by petermezei** [comment]
Another print screen about this issue:

![image](https://cloud.githubusercontent.com/assets/18461114/23170170/972a4164-f84e-11e6-9854-8d8bf396c047.png)

**Comment by attilalaszlo** [comment]
it can be related:
https://github.com/electron/electron/issues/8205

**Comment by attilalaszlo** [comment]
I could reproduce it. This is come from the getStatus call in the resources component. Till the referenced Electron issue won't be solved I just make a try catch around the status call and hide the error message. It's not a big deal if one status call will be skipped on the Resources page
