### ISSUE TITLE
PRC Service Recommend filter field does not work properly.

### ISSUE THREAD

**Issue by petermezei** [slamby/slamby-insight#6]
When we have a PRC service activated and we click the recommend button, then in the pop-up window Filter input does not work.

![image](https://cloud.githubusercontent.com/assets/18461114/21026093/7675cf36-bd8b-11e6-8b3e-0d201a9d053b.png)

Based on the API documentationt, we can use a filter object, like:

{
    "Query":"fieldName:fieldValue"
}

or

"Filter" : {
        "TagIdList" : ["1"],
        "Query" : "title:michelin"
},

So it would be nice to modify the input form from text to textarea, and be able to process the filter object:

{
        "TagIdList" : ["1"],
        "Query" : "title:michelin"
}

@attilalaszlo  could you check and validate the recommended input and input type?

@sbeci could you check it please once atis validated it?

**Comment by attilalaszlo** [comment]
Ok, I modified the filter object on the form

![image](https://cloud.githubusercontent.com/assets/16559709/21054346/9c94bfc2-be2d-11e6-8e83-761424ca29dc.png)

will be available in version 1.0.2

**Comment by petermezei** [comment]
Nice! Thanks!

**Comment by attilalaszlo** [comment]
np, version 1.0.2 is on its way
