### ISSUE TITLE
Webpack - glyphicon fonts issue

### ISSUE THREAD

**Issue by attilalaszlo** [slamby/slamby-insight#7]
The fonts are not handled correctly. I realized when I want to use a glyphicon

The font is not shown:
![image](https://cloud.githubusercontent.com/assets/16559709/21219753/5ec5c58c-c2b6-11e6-80d8-2c4b79c02d43.png)

The chrome console show me this warning:

Failed to decode downloaded font: file:///C:/git/github/slamby-insight/src/build/fonts/glyphicons-halflings-regular.ca7a66825dac5cf4cb4c99f2b45e5360.woff2
index.html:1 OTS parsing error: invalid version tag
index.html:1 Failed to decode downloaded font: file:///C:/git/github/slamby-insight/src/build/fonts/glyphicons-halflings-regular.3c3b5fb156902efccea1ef4735b8a512.woff
index.html:1 OTS parsing error: invalid version tag
index.html:1 Failed to decode downloaded font: file:///C:/git/github/slamby-insight/src/build/fonts/glyphicons-halflings-regular.663f5bfd311934c273b4ca99e4250a84.ttf
index.html:1 OTS parsing error: invalid version tag

**Comment by attilalaszlo** [comment]
this issue is low prio because we can use font-awesome instead of glyphicons

**Comment by petermezei** [comment]
branch issue/7 created and pushed. Fixed, pull request created.
